name: eval_annotation
description: dart_eval annotation library
version: 0.8.1
repository: https://github.com/ethanblake4/eval_annotation

environment:
  sdk: '>=3.4.0 <4.0.0'

dev_dependencies:
  lints: '>=4.0.0 <6.0.0'
dependencies:
  meta: ^1.8.0
